import { createHash } from 'node:crypto';import type { Action,Policy,RecoveryCase } from './types.ts';
export type AdvisorInput={schemaVersion:'1.0';caseState:RecoveryCase['state'];subscriptionState:RecoveryCase['subscriptionState'];failure:{ownership:string;remedy:string;confidence:string}|null;eligibleActions:Action[];policyVersion:string};
export type AdvisorOutput={schemaVersion:'1.0';selectedAction:Action;reasonCodes:string[];rationale:string;confidence:number;abstain:boolean};
export type Advisor={name:string;version:string;configVersion:string;rank(input:AdvisorInput):unknown};
export type AdvisoryResult={selectedAction:Action;source:'advisor'|'deterministic_fallback'|'advisor_abstention';reasonCodes:string[];rationale:string;confidence:number|null;advisorName?:string;advisorVersion?:string;configVersion?:string;inputHash:string;outputHash?:string;validationError?:string};
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');const keys=['abstain','confidence','rationale','reasonCodes','schemaVersion','selectedAction'];
export function makeAdvisorInput(c:RecoveryCase,eligible:Action[],policy:Policy):AdvisorInput{return {schemaVersion:'1.0',caseState:c.state,subscriptionState:c.subscriptionState,failure:c.failure?{ownership:c.failure.ownership,remedy:c.failure.remedy,confidence:c.failure.confidence}:null,eligibleActions:[...eligible],policyVersion:policy.version}}
function validate(value:unknown,eligible:Action[]):{ok:true;value:AdvisorOutput}|{ok:false;error:string}{if(!value||typeof value!=='object'||Array.isArray(value))return {ok:false,error:'output_not_object'};const v=value as Record<string,unknown>;if(JSON.stringify(Object.keys(v).sort())!==JSON.stringify(keys))return {ok:false,error:'unexpected_or_missing_fields'};if(v.schemaVersion!=='1.0'||typeof v.selectedAction!=='string'||!eligible.includes(v.selectedAction as Action))return {ok:false,error:'action_not_eligible'};if(!Array.isArray(v.reasonCodes)||!v.reasonCodes.every(x=>typeof x==='string')||typeof v.rationale!=='string'||v.rationale.length>280||typeof v.confidence!=='number'||v.confidence<0||v.confidence>1||typeof v.abstain!=='boolean')return {ok:false,error:'invalid_field'};return {ok:true,value:v as AdvisorOutput}}
export function advise(c:RecoveryCase,eligible:Action[],policy:Policy,fallback:Action,advisor?:Advisor):AdvisoryResult{const input=makeAdvisorInput(c,eligible,policy),inputHash=hash(input);if(!advisor)return {selectedAction:fallback,source:'deterministic_fallback',reasonCodes:['NO_ADVISOR_CONFIGURED'],rationale:'Fixed-rule selector used.',confidence:null,inputHash};let raw:unknown;try{raw=advisor.rank(input)}catch{return {selectedAction:fallback,source:'deterministic_fallback',reasonCodes:['ADVISOR_UNAVAILABLE'],rationale:'Advisor failed; fixed-rule selector used.',confidence:null,advisorName:advisor.name,advisorVersion:advisor.version,configVersion:advisor.configVersion,inputHash,validationError:'advisor_threw'}}const checked=validate(raw,eligible),outputHash=hash(raw);if(!checked.ok)return {selectedAction:fallback,source:'deterministic_fallback',reasonCodes:['ADVISOR_OUTPUT_REJECTED'],rationale:'Invalid advisor output; fixed-rule selector used.',confidence:null,advisorName:advisor.name,advisorVersion:advisor.version,configVersion:advisor.configVersion,inputHash,outputHash,validationError:checked.error};const out=checked.value;if(out.abstain||out.confidence<0.6){const selected=eligible.includes('WAIT')?'WAIT':fallback;return {selectedAction:selected,source:'advisor_abstention',reasonCodes:[...out.reasonCodes,'ADVISOR_ABSTAINED'],rationale:out.rationale,confidence:out.confidence,advisorName:advisor.name,advisorVersion:advisor.version,configVersion:advisor.configVersion,inputHash,outputHash}}return {selectedAction:out.selectedAction,source:'advisor',reasonCodes:out.reasonCodes,rationale:out.rationale,confidence:out.confidence,advisorName:advisor.name,advisorVersion:advisor.version,configVersion:advisor.configVersion,inputHash,outputHash}}
