import { createHash } from 'node:crypto';import type { Action,AuditEvent,RecoveryCase } from './types.ts';import type { Store } from './store.ts';
export type MerchantRole='merchant_operator'|'merchant_admin';export type RecoveryDestination={mode:'simulated'}|{mode:'trusted_url';url:string};export type MessagePreview={templateVersion:string;channel:'simulated_email';subject:string;body:string;recoveryDestination:RecoveryDestination};
const contactActions:Action[]=['SEND_GENTLE_REMINDER','SEND_ACTION_REQUIRED','SURFACE_PAYMENT_UPDATE_LINK'];const hash=(s:string)=>createHash('sha256').update(s).digest('hex').slice(0,20);
export function validateRecoveryUrl(url:string,allowedDomains:string[]):boolean{try{const parsed=new URL(url);return parsed.protocol==='https:'&&parsed.username===''&&parsed.password===''&&allowedDomains.some(domain=>parsed.hostname===domain||parsed.hostname.endsWith(`.${domain}`))}catch{return false}}
export function preview(action:Action,destination:RecoveryDestination={mode:'simulated'}):MessagePreview|null{if(!contactActions.includes(action))return null;if(destination.mode==='trusted_url'&&!validateRecoveryUrl(destination.url,['razorpay.com']))throw new Error('untrusted recovery URL');const copy:Record<string,{subject:string;body:string}>={SEND_GENTLE_REMINDER:{subject:'A gentle payment reminder',body:'Your recent subscription payment was not completed. Please review your payment method when convenient.'},SEND_ACTION_REQUIRED:{subject:'Action needed for your subscription payment',body:'Your subscription payment needs your attention. Please use the approved recovery flow to review your payment method.'},SURFACE_PAYMENT_UPDATE_LINK:{subject:'Update your payment method securely',body:'Please use the merchant-approved secure recovery flow to update your payment method.'}};return {templateVersion:'recovery-en-v1',channel:'simulated_email',...copy[action]!,recoveryDestination:destination}}
export class MerchantExperience{readonly store:Store;constructor(store:Store){this.store=store}
 queue(){return (this.store.db.prepare('SELECT id,data FROM cases ORDER BY json_extract(data,\'$.state\'),id').all() as {id:string;data:string}[]).map(row=>{const c=JSON.parse(row.data) as RecoveryCase;return {id:c.id,state:c.state,subscriptionId:c.subscriptionId,amountMinor:c.amountMinor,currency:c.currency,contactCount:c.contactCount}})}
 suppress(caseId:string,role:MerchantRole,at:string){if(!['merchant_operator','merchant_admin'].includes(role))throw new Error('forbidden');const c=this.store.getCase(caseId);if(!c)throw new Error('case not found');if(c.state==='RECOVERED'||c.state==='CLOSED_CANCELLED')throw new Error('case terminal');if(c.state!=='SUPPRESSED')this.store.saveCase({...c,state:'SUPPRESSED'});this.audit(caseId,c.latestEventId,at,'CASE_SUPPRESSED',{role});return this.store.view(caseId)}
 override(caseId:string,action:Action,role:MerchantRole,at:string){if(role!=='merchant_admin')throw new Error('forbidden');const view=this.store.view(caseId);if(!view.case)throw new Error('case not found');if(['RECOVERED','CLOSED_CANCELLED','SUPPRESSED'].includes(view.case.state))throw new Error('case terminal');const latest=view.decisions.at(-1);if(!latest?.eligibleActions.includes(action))throw new Error('action not eligible');const key=`override:${caseId}:${latest.id}:${action}`;if(contactActions.includes(action)){const message=preview(action);this.store.enqueue(`out_${hash(key)}`,key,caseId,action,{simulated:true,message,override:true})}else if(action==='ESCALATE_TO_MERCHANT')this.store.enqueue(`out_${hash(key)}`,key,caseId,action,{simulated:true,override:true});this.audit(caseId,latest.eventId,at,'OVERRIDE_RECORDED',{role,action,dispatchKey:key});return this.store.view(caseId)}
 markDelivered(outboxId:string,role:MerchantRole,at:string){if(!['merchant_operator','merchant_admin'].includes(role))throw new Error('forbidden');const row=this.store.outboxItem(outboxId);if(!row)throw new Error('outbox item not found');this.store.markOutboxDelivered(outboxId);this.audit(row.case_id,'simulated_delivery',at,'DELIVERY_UPDATED',{outboxId,status:'SIMULATED_DELIVERED',role});return this.store.view(row.case_id)}
 private audit(caseId:string,eventId:string,at:string,kind:AuditEvent['kind'],detail:Record<string,unknown>){this.store.audit({id:`aud_${hash(`${caseId}:${eventId}:${kind}:${JSON.stringify(detail)}`)}`,caseId,eventId,at,kind,detail})}}
