import { createHash } from 'node:crypto'; import { advise,type Advisor } from './advisor.ts'; import { normalizeFailure } from './normalize.ts'; import { evaluate,isContact,prohibited,selectAction } from './policy.ts'; import type { AuditEvent,CaseState,Decision,Outcome,Policy,RecoveryCase,RecoveryEvent } from './types.ts'; import { Store } from './store.ts';
const rank:Record<string,number>={unknown:0,pending:1,paused:2,halted:3,active:4,cancelled:5};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex').slice(0,20);
export class Pipeline{readonly store:Store;readonly policy:Policy;readonly advisor?:Advisor;constructor(store:Store,policy:Policy,advisor?:Advisor){this.store=store;this.policy=policy;this.advisor=advisor}
 process(e:RecoveryEvent,now=e.receivedAt){const caseId=`${e.merchantId}:${e.subscriptionId}`;this.addAudit(caseId,e,'EVENT_RECEIVED',{});if(!this.store.ingest(e)){this.addAudit(caseId,e,'DUPLICATE_IGNORED',{});return this.store.view(caseId)}
  const old=this.store.getCase(caseId);const nextSub=this.subState(e);const stale=Boolean(old&&new Date(e.occurredAt)<new Date(old.stateOccurredAt));let c:RecoveryCase;
  if(old&&(stale||rank[nextSub]<rank[old.subscriptionState])){c=old;this.addAudit(caseId,e,'STALE_EVENT_IGNORED',{incoming:nextSub,current:old.subscriptionState});}
  else{const failure=e.rawFailure?normalizeFailure(e.rawFailure):old?.failure;const state=this.caseState(e,nextSub,failure?.contradictory??false);c={id:caseId,merchantId:e.merchantId,subscriptionId:e.subscriptionId,customerRef:e.customerRef,state,subscriptionState:nextSub,stateOccurredAt:e.occurredAt,amountMinor:e.amountMinor,currency:e.currency,contactCount:old?.contactCount??0,latestEventId:e.eventId,...(old?.lastContactAt?{lastContactAt:old.lastContactAt}:{}),...(failure?{failure}:{})};this.store.saveCase(c);this.addAudit(caseId,e,'PROJECTION_UPDATED',{state});}
  const result=evaluate(c,e,this.policy,now),fallback=selectAction(result.eligible),advisory=advise(c,result.eligible,this.policy,fallback,this.advisor),selected=advisory.selectedAction;const d:Decision={id:`dec_${hash(e.eventId)}`,caseId,eventId:e.eventId,policyVersion:this.policy.version,decidedAt:now,eligibleActions:result.eligible,selectedAction:selected,prohibitedActions:prohibited(result.eligible),reasonCodes:[...result.reasons,...advisory.reasonCodes],selectorVersion:this.advisor?'advisor-gate-v1':'fixed-v1',selectionSource:advisory.source,rationale:advisory.rationale,confidence:advisory.confidence,inputHash:advisory.inputHash,...(advisory.advisorName?{advisorName:advisory.advisorName}:{}),...(advisory.advisorVersion?{advisorVersion:advisory.advisorVersion}:{}),...(advisory.configVersion?{advisorConfigVersion:advisory.configVersion}:{}),...(advisory.outputHash?{outputHash:advisory.outputHash}:{}),...(advisory.validationError?{validationError:advisory.validationError}:{})};this.store.saveDecision(d);this.addAudit(caseId,e,'DECISION_RECORDED',{selected,eligible:result.eligible,selectionSource:advisory.source,validationError:advisory.validationError??null});
  if(isContact(selected)||selected==='ESCALATE_TO_MERCHANT'){const key=`${caseId}:${e.eventId}:${selected}`;this.store.enqueue(`out_${hash(key)}`,key,caseId,selected,{simulated:true,customerRef:e.customerRef});if(isContact(selected)){c={...c,contactCount:c.contactCount+1,lastContactAt:now};this.store.saveCase(c)}this.addAudit(caseId,e,'OUTBOX_ENQUEUED',{selected});}
  const status:Outcome['status']=c.state==='RECOVERED'?'RECOVERED':c.state==='CLOSED_CANCELLED'?'CANCELLED':selected==='SUPPRESS'?'SUPPRESSED':'OPEN';const o:Outcome={id:`outcome_${hash(e.eventId)}`,caseId,eventId:e.eventId,status,occurredAt:now,attribution:status==='RECOVERED'?'platform_or_spontaneous':'none',...(status==='RECOVERED'?{recoveredAmountMinor:e.amountMinor}:{})};this.store.outcome(o);this.addAudit(caseId,e,'OUTCOME_RECORDED',{status});return this.store.view(caseId)}
 private subState(e:RecoveryEvent){return ({'subscription.pending':'pending','subscription.charged':'active','subscription.halted':'halted','subscription.cancelled':'cancelled','subscription.paused':'paused','subscription.resumed':'active',invalid:'unknown'} as const)[e.type]}
 private caseState(e:RecoveryEvent,s:string,contradictory:boolean):CaseState{if(e.type==='invalid'||e.identityConsistent===false||contradictory)return 'AMBIGUOUS';return s==='pending'?'OPEN_PENDING':s==='halted'?'OPEN_HALTED':s==='active'?'RECOVERED':s==='cancelled'?'CLOSED_CANCELLED':e.suppressed?'SUPPRESSED':'AMBIGUOUS'}
 private addAudit(caseId:string,e:RecoveryEvent,kind:AuditEvent['kind'],detail:Record<string,unknown>){this.store.audit({id:`aud_${hash(`${e.eventId}:${kind}:${JSON.stringify(detail)}`)}`,caseId,eventId:e.eventId,at:e.receivedAt,kind,detail})}}
